language: node_js
node_js:
- node
sudo: false
install: yarn install
script:
- echo "skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: "dwIVoNPyDMw1vPEDbbhqvLbaYzwJTmCdKUaAQpinMbTtQR6CRRsGtgcMQeD3BbUHLb6hXOY1OTZJuM22In9q4CC96AhCJwue1TdpqrU14EZZaxdnIpLtcs52EKUk8YlM3gfBd21b/LvnG8qF2ryZEBBWj4E362eUZd+igO+DEZ8Q8VapqMPpyOG61VdYKaXsDLTHbIq6cbUD0Q5/SDCTa9gNyBCeyolDcPhxwmLkuEACbfOoTNKAkqqZm4g3eJ4bDbYGUIpHSLbmUt5v29yMBmy5cnI1fX0YlZPj98/yKvFCIxlF/kTfnoJNZBnzY7tlg6xrkfC2wWmH26yKYhn9cxMkrLlUCJqFNYXECu4uC10mE0xQ+VwZysMtAIhfQBkuA48/TdoezJ9qsFP1Ch2aKcAoCFxDHcwDMu1el/FlITaJNa5sRJvjrwUgRdblUTa2gIi5AFPSBb+hS9U7/zdkaivQ9plvViC5vhwt4eyfI1nBuFLZt8G2zd6nklG0r6T36BvDyrpUZaQqLugtYgsADejjjwhXe/yq7H6vzY8aS6XDMn4KWgGmsX66bmAbsRQC9ebZzcdyxZ5RsqIEnVxpIJWyW9OwpS7I+McMrq969PjqRMWE9sWu2z3s7E7sgh4MUpjtO3JKaa6RW8O9RxgZ3S4CDYiK+9jzh5bHpcX0qA0="
  app: node-express-postgre
  on:
    repo: alpersonalwebsite/node-express-postgre
  api_key:
    secure: xKzmMY4dkJxKu/ADAbP4UAahml1Egbzg3/BmaSAOZJyd1MxMwTAy/RWKzNFBsBwRNnrIADOJqU3KACee92XJ/Uec49iqsF8Ml5HKTv894LVjvteJZpG0DhC1NQfQ18Pf99w1eBYGd1kavd8ttr9CbRwDVboQAe5JPRmWSxzyzsMVC4FMlgwSjEN8DMUpm2l8z7YFFs9u2IDJ+KzjEBX3EGo9kiWEv/Al4jfHpcP7FFeZ1BVS0QyQG6H3rz4p6kUZpLlcoxwNsXu6dTlFDBlN2AdlCddYxOFB/LyPt6cPOXc4S+SThSznTrRm0uMXqBuopHk6WilYcqlmSqmSC9I0dF0yAjWBbWL7VxPLehJ9mHYChlmS0RPhgjGhIFjvCY1lGh8XJ7QFFkviiP7G9YbhBjEzQXkjjUjmQvfIl4YcruHMKIACe/FIJFryBSEw4x9uq+l3AMoh+ZT0oJAIC8V14+umJFc9eUwcOw1nLWLTrblEBNS/pOt6AKcSYazhgqOGB8srx3WMiGXjvcL8BKDxwNDBWJxn/1DZ0IdmaNcWNKZBR2RaZauXfmBwomZ16DMMn8B1dym7jT4GNSG6sH849T3cQcGC8Q8wEQW72E61rn4UWMiHPzmH4uxP3KulLjMmKOeaFr9++Zx+1KkauXR4p7eNtcXYePHncHMavI26PsA=
