language: node_js
node_js:
- node
sudo: false
install: yarn install
script:
- "yarn run lint"
- echo "skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: "CYE54d0l/zwucUwW8HoBpz1YxC/ZUV2PDCO0292G04PoUKvu40FK2f7I/8D8RpHo8sIxmJ1z2A9GjHbesnHBmQ3Y9np6ey2WJtktxwPcrikM/OAaV2N9OAnq5LkTu/opCYOEY1rMFCMNyrgRaUSSB7vTrvRtKdxEE/18mOflf/Xk8eeFLGUP+eCZQPzqHoQFE6K5UbhDSbjTfPffO/583qPNregQ8ChW86SuABw9AjRc+sCKsinHJ7Ihx5HyIqyjFj2nwGyltsh8ozhAD+9iFuvXoCZvUwR79tdo680e+JY3Cb/6yI+u7ewBmB5GPgaLrdEfFtdhT2joDN52Tpj7U+HqY4OHQaTMCK9MyivOSqY/EPtJVD8lhWPLkAmubT+lfGX3+pmXD8SRmLqBRgO+QHg7rIir+EOIq6ezLW0hOzckppUSCU5m4uSL8Mvbgr2TZRE0a7yx1gyZkLICB46GOKmg9Qs/jIrlVYY8qx+0guxC7S7pzHxVsrZmRctDqkleRlt1DlNEFYStJjhJ1d5vSDZGTYpUlrQd8DID/V9L2tzp8G8kJSf10ti+djGQNV8U+TBOuYMKEcWavTZxRlz5cvj/HdbM/waFp9XcU/R+H6VvVtBH3G9ocxfZmXis7nRqFCk5fpj6KFMxEefENpTT0tCc5KDBe5yBG18pxSu6EeA="
  app: node-express-postgre
  on:
    repo: alpersonalwebsite/node-express-postgre